### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by ryan-byrnes** [ryan-byrnes/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Set up HTML skeleton
- [x] Find car image
- [x] Insert car image and style with CSS until document looks like example
