### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by ryan-byrnes** [ryan-byrnes/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create new CSS rule sets for classes that will rotate the car image in 90 degree increments
- [x] Create JS function that will turn car correctly based on the keypress
- [x] Set keypresses for arrow keys as well as for wsad
- [x] Add event listener to handle functionality
